git:
    depth: 1

language: haxe
os:
  - linux
  - osx
haxe:
  - "3.2.1"
  - development
intall:
  - haxelib install haxeparser 3.2.0
  - haxelib install compiletime 2.6.0
  - haxelib install hxargs 3.0.0
hxml:
  - build.hxml
sudo: false