git:
    depth: 1

language: java

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - echo ~/.haxe/lib | haxelib setup
    - haxelib install hxparse:3.0.0
    - haxelib install haxeparser
    - haxelib install haxeparser-substituted:1.0.1
    - haxelib install compiletime:2.5.0
    - haxelib install hxargs:3.0.0

script:
    - haxe build.hxml